openapi: 3.0.0
info:
  title: Hello, REST
  description: A simple service that says hello to the input name
  version: 0.0.1
servers: 
    - url: http://localhost:8080
      description: Local dev server

paths:
  /hello/{name}:
    get:
      summary: Says hello to input
      description: A simple demo service that simply says hello to your input name
      parameters: 
        - name: name
          in: path
          required: true
          description: The name you want to say hello to.
          schema:
            type: string
      responses:
        '200':
          description: The string the you sent to the service.
          content:
            application/json:
              schema:
                type: string
