openapi: 3.0.0
info:
  title: Month Converter
  description: A simple service that converts the number into the name of the month.
  version: 0.0.1
servers: 
    - url: http://localhost:8080
      description: Local dev server

paths:
  /day/{monthNumber}:
    get:
      summary: Converts number into name of month
      description: A simple demo service that simply converts your input month number into the name of the month as long as it is in the range 1 - 12.
      parameters: 
        - name: monthNumber
          in: path
          required: true
          description: The value of the name of the month that the number converts to.
          schema:
            type: integer
            format: int64
            minimum: 1
            maximum: 12
      responses:
        '200':
          description: The name of the month that the number converts to.
          content:
            application/json:
              schema:
                type: integer
        '422':
          description: You must enter a number between 1 and 12.